# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://yogeshjain96.github.io/hugo-paper-event/"
title: PaperEvent
copyright: "© [PaperEvent](https://github.com/yogeshjain96/hugo-paper-event/graphs/contributors)"
theme: ["PaperEvent"]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "paper-event"]

minify:
  disableXML: true
  # minifyOutput: true

pagination:
  disableAliases: false
  pagerSize: 5

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: "\U0001F50D"
          url: search
          weight: 1
        - identifier: meetups
          name: Meetups
          url: /meetups/
          weight: 20
        - identifier: register
          name: Register
          url: /register/
          weight: 80
        - identifier: call-for-papers
          name: CFP
          url: /call-for-papers/
          weight: 90
        - identifier: schedule
          name: Schedule
          url: /schedule/
          weight: 95
        - identifier: members
          name: About
          url: /about/
          weight: 100
        - identifier: speakers
          name: Speakers
          url: /speakers/
          weight: 99
    params:
      profileMode:
        enabled: true
        title: PaperEvent
        imageUrl: "https://raw.githubusercontent.com/googlefonts/noto-emoji/master/svg/emoji_u1f9d1_1f3fb_200d_1f4bb.svg"
        imageTitle: ProfileMode image
        imageWidth: 120
        imageHeight: 120
        subtitle: |
          **PaperEvent** - Event and Conference Hugo Theme

          This theme is designed to be used for events, conferences, meetups, & more.
          This is a sample event site.
          Feel free to use this **opensource theme** to get started with your event site.
      buttons:
      - name: Submit paper
        url: call-for-papers
      - name: Register
        url: register
      - name: Schedule
        url: schedule

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Theme PaperEvent - https://github.com/YogeshJain96/hugo-paper-event"
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: false
  # disableSpecial1stPost: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowPageNums: true
  ShowToc: false
  images: ["images/paper-event-cover.png"]

  profileMode:
    enabled: false
    title: PaperEvent
    imageUrl: "#"
    imageTitle: my image
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Submit paper
        url: call-for-papers
      - name: Register
        url: register
      - name: Schedule
        url: schedule
  socialIcons:
    - name: linkedin
      title: LinkedIn Group
      url: "#"
    - name: youtube
      title: YouTube Channel
      url: "#"
    - name: email
      title: Email Us
      url: "mailto:xyz@gmail.com"
    - name: github
      title: View Source on Github
      url: "https://github.com/YogeshJain96/hugo-paper-event/tree/example-site"
  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true
